### ISSUE TITLE
Delete hotkey & Multiselection

### ISSUE THREAD

**Issue by kompots** [DurtyFree/durty-cloth-tool#101]
Would it be possible to add key stroke listener for delete on left side list?

**Comment by kompots** [comment]
Also multi select would be very very usefull

**Comment by DurtyFree** [comment]
You mean a DEL hotkey for deleting? Its planned for next update. There will also be multi selection & multi deletion in the next update

**Comment by DurtyFree** [comment]
DEL hotkey, supporting multi selection, will be available next update.

**Comment by DurtyFree** [comment]
Introduced in v2.5.0, feel free to check it out & download here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.0
