### ISSUE TITLE
[Feature request] Error & warning list

### ISSUE THREAD

**Issue by william-des** [DurtyFree/durty-cloth-tool#102]
It would be usefull to have a list of all the errors and warnings, similar to what you have in IDEs like Visual Studio, when working with a large cloth pack.
Ideally you'll be able to filter displayed errors types, and clicking on an error would select the related clothing item.

**Comment by DurtyFree** [comment]
Indeed very good feature request and something I have also been thinking of as an addition.

Will be added in the future, thanks for the request:)

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
