### ISSUE TITLE
[Feature request] Drawables filters

### ISSUE THREAD

**Issue by william-des** [DurtyFree/durty-cloth-tool#104]
I think that this was already asked on the discord server but I'm submitting this here because github issues are easier to track.

It would be great to be able to filter the displayed drawables on the main list per gender and cloth type.

Don't worry, this is my last suggestion (for today) 😅

**Comment by zoovenem** [comment]
I agree with this, 

having expandable and collapsible "folders" on the left that you can choose to hide per component and per gender in a hierarchy would be brilliant.

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
