### ISSUE TITLE
replace dlc for fivem

### ISSUE THREAD

**Issue by LalinDurukan** [DurtyFree/durty-cloth-tool#107]
the "dlc replace" feature for fivem is not working. when i enter the game i still see the game's clothes instead of the clothes i added.

**Comment by LalinDurukan** [comment]
I've tried a few. maybe I'm making a mistake. there could be a tutorial on this.

**Comment by DurtyFree** [comment]
We have investigated this further and it really seems like some of our cloth collection names are wrong for replace - Will fix this in next update

**Comment by LalinDurukan** [comment]
thank you!

**Comment by DurtyFree** [comment]
This has been fixed in a recent update.
