### ISSUE TITLE
_r and _u for pants

### ISSUE THREAD

**Issue by sangyoo91** [DurtyFree/durty-cloth-tool#11]
Some pants and shoes do not need the _r (race) tag meaning, they don't have skin info on the texture side of things.

These _u typed pants and shoes I assume have different structures in the YMT as well.

I'm looking for someone who might want to work with me on this.

Simply renaming them causes problems while they do still load ingame (_u => _r).

**Comment by DurtyFree** [comment]
This might be related to the texId additionally set in the ymt, its connected to the prefixes somehow

**Comment by DurtyFree** [comment]
Pls try with latest version: https://github.com/DurtyFree/altv-cloth-tool/releases/tag/1.3

**Comment by sangyoo91** [comment]
I'll try it out!!

**Comment by sangyoo91** [comment]
I've tried with `_u` shoes right now. The export result is `feet_xxx_r` with textures ending with `feet_diff_xxx_uni`.

While this still does work, it doesn't solve the main problem which `feet_xxx_r` should be paired with `feet_diff_x_whi(racetag)`
and `feet_xxx_u` paired with `feet_diff_xxx_uni`.

While some models will still work this way, some models still load slowly. I don't know what the root cause of this is, but from experience and vigorous testing, I believe somewhere in the ymts or what not, theres a difference between how `_u` and `_r` models work when defined.

Also, apparently `_u` models support better texture loading with higher res/file size. This is not confirmed by me, but that's what a lot of modelers in the gta modding community believe thru their testing.

Thank you! And let me know if I can help in any way :D

**Comment by sangyoo91** [comment]
And on another note, it would be nice if the tool automatically renamed texture tags on build base on model tag.

if model ends with `_r` -> rename `_uni` to `_whi`

vice versa.

**Comment by DurtyFree** [comment]
Thanks for the feedback, would love to hear from you on discord, my tag is DurtyFree#3216

**Comment by sangyoo91** [comment]
@DurtyFree Friend requested on Discrod. GG777#7777

**Comment by DurtyFree** [comment]
Fixed in next release, keep an eye on https://github.com/DurtyFree/durty-cloth-tool/releases

**Comment by DurtyFree** [comment]
Latest version that should fix this is now available here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.1
