### ISSUE TITLE
[Feature Request] Manual texture re-ordering

### ISSUE THREAD

**Issue by Pebble-s** [DurtyFree/durty-cloth-tool#110]
Add additional ways to manually re-order texture files within the tool;
-  Drag and drop ordering OR text box input/something similar

Either of these methods would speed up texture ordering massively and the current method results in false duplicates while reordering, These are only visual however for newer/inexperienced clothing tool users this could be confusing. 
Example of duplicates: https://prnt.sc/u4F8tfWWOFDW

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
