### ISSUE TITLE
[Feature Request] Key shortcuts to actions

### ISSUE THREAD

**Issue by LYRYCAL** [DurtyFree/durty-cloth-tool#111]
It will be very helpful & save much time.

**Comment by DurtyFree** [comment]
Shortcut to what?

**Comment by 19adorest** [comment]
Like example CTRL+O to optimize texture and something like that, that will save much time.

**Comment by DurtyFree** [comment]
I see, do you have suggestions for some shortcuts?

**Comment by Gameadictive** [comment]
A search option, a model viewer with a click option and everytime u click on some clothe the viewer changes so u dont need to stay click enter.

**Comment by TayMcKenzieNZ** [comment]
CTRL + S = Save Project

Perhaps CTRL + O would be for opening project though? Or CTRL + P?

**Comment by Gameadictive** [comment]
I mean some kind of search drawable feature.

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
