### ISSUE TITLE
[Feature Request] Drawable Counter

### ISSUE THREAD

**Issue by Pebble-s** [DurtyFree/durty-cloth-tool#112]
Add tracking with a visible counter for how many overall drawables of each type you've added to your clothing pack.

For example, if you click on a Jbib it'll state you have "x/128 Total Jbib's" This will make it easier for people to keep track of how many drawables of each type they're adding to their clothing packs which hopefully will cause fewer headaches for many in the discord having to remind people there is a 128 limit!

**Comment by DurtyFree** [comment]
Actually a warning should popup as soon as you hit the limit of 128 total jbibs per gender, but I think this can be part of the UI Update containing #71 and #104

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
