### ISSUE TITLE
[Feature Request] Coloured labels NTH

### ISSUE THREAD

**Issue by zoovdev** [DurtyFree/durty-cloth-tool#114]
Use coloured & styled icons to allow for easier to digest symbols in the array of drawables 

![Photoshop_zqojdEvAqO](https://user-images.githubusercontent.com/84139171/222917387-8a96d042-a628-47d7-94cb-10cd8729ee13.png)

Low Priority of course, but is just a nice to have and should add some very easily noticeable differences between gender, warnings and types.

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
