### ISSUE TITLE
[Feature Request] Preview drawables with pressing enter

### ISSUE THREAD

**Issue by scherex** [DurtyFree/durty-cloth-tool#122]
There should be the possibility to scroll through the drawables using the arrow keys and see the 3D preview with pressing the enter key.

**Comment by DurtyFree** [comment]
Just for completion; "fast way" of previewing clothes is currently double clicking an item. 
I will consider adding the possibility for using arrow keys + ENTER for previewing

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
