### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by drK-208** [DurtyFree/durty-cloth-tool#123]
I have the following error:
System.ArgumentException: Caracteres no válidos en la ruta de acceso.
   en System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
   en System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
   en System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   en System.IO.Path.GetFullPathInternal(String path)
   en System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   en System.IO.File.Copy(String sourceFileName, String destFileName)
   en altClothTool.App.Builders.AltvResourceBuilder.CopyClothTextureToResource(String clothTextureFilePath, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix, String ytdPostfix, Char offsetLetter) en H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\AltvResourceBuilder.cs:línea 63
   en altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) en H:\DevProjects\GIT_Projects\altv-cloth-tool
\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:línea 56
   en altClothTool.App.ClothesResourceBuilderFactory.BuildResource(Targe

tResourceType resourceType, String outputFolder, String collectionName) en H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:línea 18

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

Its a huge pack but here is the project file

Here is the .json file
[tggits.altv-cloth.zip](https://github.com/DurtyFree/durty-cloth-tool/files/11240392/tggits.altv-cloth.zip)

**Comment by DurtyFree** [comment]
Please use latest version of the tool
