### ISSUE TITLE
Clothes texture bug

### ISSUE THREAD

**Issue by erwinana97** [DurtyFree/durty-cloth-tool#124]
Hello,
after creating a pack with this tool, some clothes are completely black. 
![image](https://user-images.githubusercontent.com/114339729/232439993-97c008d9-8de4-498b-99e2-41a5229a5739.png)
![image](https://user-images.githubusercontent.com/114339729/232440059-bb0627b0-2cda-4882-a50d-e96aad68e5fc.png)
I have tryed it with activated the flag, that there is a skintone and without the flag.
Did I do something wrong or is there a solution for this
What surprised me is that some see the clothes normally with color and some don't
I thank you for any help

**Comment by DurtyFree** [comment]
This is either related to the cloth drawable model itself (wrong sampler configuration) or a FiveM issue (there was one in the past related to this)

Pls use the support channel in our Discord to get further help @  https://discord.plebmasters.de
