### ISSUE TITLE
Tattoo Scale Y resets back to default occasionally

### ISSUE THREAD

**Issue by zanedii** [DurtyFree/durty-cloth-tool#125]
Noticed a weird issue today when creating some addon tattoos. Occasionally the "Scale Y" resets back to the default value of 0.05. Will try to find steps to reproduce, although it should be reproduceable by just creating multiple new tattoos and changing the values.

**Comment by DurtyFree** [comment]
Ah i see, thank you for reporting!

**Comment by DurtyFree** [comment]
Couldnt reproduce this, please retest with most recent version :)
