### ISSUE TITLE
[Feature request] Standard optimize settings (DX11) configurable

### ISSUE THREAD

**Issue by lLukDreams** [DurtyFree/durty-cloth-tool#126]
Already asked about this in the Discord, but here again to keep track,
for my server it aint the best option with dx11 since a lot of people are using dx10 (Geringverdiener) and would like to have the option to set a standard myself, so I can spare some time changing every time my choice of compression

**Comment by lLukDreams** [comment]
it is kinda of an issue at the same time since it cost me extra time. xD

**Comment by DurtyFree** [comment]
This is something that is planned with an future update where optimization presets + warning thresholds can be configured manually per project.

Thanks for the request!

**Comment by DurtyFree** [comment]
Next update will allow to set whether DX11 optimizing is preferred / should be default or not

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
