### ISSUE TITLE
[Feature Request] Texture Preview 

### ISSUE THREAD

**Issue by Pebble-s** [DurtyFree/durty-cloth-tool#131]
Add a static texture preview window (not on the 3D model, Just a view of the texture itself)

Sometimes you're unable to see textures on models in the current version of DCT due to creator-caused issues which then results in you having to open the textures in a third party program which adds a significant amount of time to your projects so having a texture viewing window within DCT would be helpful! If considered, I think it could potentially fit here 
![image](https://github.com/DurtyFree/durty-cloth-tool/assets/106319914/a3420a81-4b91-4040-9e58-c159646634a0)

**Comment by DurtyFree** [comment]
Very nice feature request, thanks! Also like the UI concept, will definetely consider adding something like this.

Somehow related to: #103 #105 (for reference)

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
