### ISSUE TITLE
[Feature request] Simpler way of sharing projects

### ISSUE THREAD

**Issue by Volt105** [DurtyFree/durty-cloth-tool#134]
had a quick question on durthy and using it for online servers with multiple devs wokring on the same project. This is just a suggestion and ik most likely wont come into place but im sending anyway. basically what im trying to explain is a group feature where you can work on durthy in a group of course only with the premium version so you guys are making money or even make a  new level with this feature
just asking because out server atm is really hard to run with multiple devs on the clothing aspect because we cant all push stuff to the server with durthy because it makes it all funky

**Comment by DurtyFree** [comment]
Hi, thanks for this great idea.

Indeed I had some concepts already for this, will definetely keep this some where on the roadmap

**Comment by DurtyFree** [comment]
Next update will introduce a new project export format that can be used to easily export & import projects / to share those.

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
