### ISSUE TITLE
Behaviour Options Check Boxes

### ISSUE THREAD

**Issue by MidnightGamingNetwork** [DurtyFree/durty-cloth-tool#136]
After saving and opening a project back up, I have notice that the behaviour check boxes will default back to the "Default begaviour" check box. But in the save file, its still saved correctly just not displaying correctly sometimes. I will attach a photo.

![bugbugbug](https://github.com/DurtyFree/durty-cloth-tool/assets/91412672/d3335738-5fcf-4735-9a96-10343f49b63d)

**Comment by DurtyFree** [comment]
Great find, will look into this! Thanks

**Comment by DurtyFree** [comment]
Fixed with upcoming update
