### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Salumkas1223** [DurtyFree/durty-cloth-tool#137]
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at q9DXreEXx7wa4Ksa7r9.zFTF67EMAWhaIXhHIyZ.AX9jnbdyEOEHEaFY8WFW(Object , Object )
   at q9DXreEXx7wa4Ksa7r9.zFTF67EMAWhaIXhHIyZ.HDmEPSCWHL(FVDAR4Inbhj2HAlCE09  , String  , String  , String  , String  , ProgressDialog  )
```

App Version: **2.5.1.0**
Items: **1 project items (1C / 0D)**
Project targets: **3**
DLC name: **test**
Collection name: **clothespack48 // **
Project path: **C:\Users\marce\Desktop\clothesprojekte\clothproject_test**
Output path: **C:\Users\marce\Desktop\clothesprojekte**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here]`

**Comment by DurtyFree** [comment]
Hmm I will have eto check this, thanks for reporting!

**Comment by M1raclee** [comment]
I wanted to try the application before buying a license, but I also got this exception.
Could you please tell me when you plan to release a new version?

**Comment by DurtyFree** [comment]
ETA is next month

**Comment by DurtyFree** [comment]
Please test with the latest minor hotfix v2.5.1.1 @M1raclee, if the auto updater doesnt run, please download manually from here: https://assets.plebmasters.de/durtyclothtool/upd/v2511/DurtyClothTool.App.zip
