### ISSUE TITLE
Limit for props

### ISSUE THREAD

**Issue by Edvesse** [DurtyFree/durty-cloth-tool#140]
Hello,

For added clothes, I know that the limit is 128, but for props (p_head), do you know what the limit is? Because I'm at 67 in my ymt, if I add one more, from the 25th I no longer have a helmet, and if I separate in another ymt it's the same.

Thanks you in advance

**Comment by DurtyFree** [comment]
Please read the wiki: https://github.com/DurtyFree/durty-cloth-tool/wiki/YMT-game-limit-and-crash-issues#255-props-hats-etc-per-gender-total

Best regards
