### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by Paradox4578** [DurtyFree/durty-cloth-tool#147]
I have the following error:
System.UnauthorizedAccessException: Toegang tot het pad C:\mp_m_freemode_01_mp_m_nike_tech.meta is geweigerd.
   bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bij System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   bij System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   bij System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   bij System.IO.File.WriteAllText(String path, String contents)
   bij altClothTool.App.Builders.FivemResourceBuilder.OnResourceClothDataFinished(String outputFolder, Int32 sexNr, String collectionName, Boolean isAnyPropAdded, Boolean isAnyClothAdded) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\FivemResourceBuilder.cs:regel 83
   bij altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:regel 104
   bij altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:regel 28

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Make sure to have access to the files you add, the folder you save / build to or try to run as admin.
