### ISSUE TITLE
Texture Downscale does not work

### ISSUE THREAD

**Issue by vanlueckn** [DurtyFree/durty-cloth-tool#148]
If i activate "downscale texture" the texture does not resize and keeps its old size.

Version 2.5.1.1

**Comment by DurtyFree** [comment]
Check the logs (click on bottom section in the tool), this is most likely due to a broken texture / invalid mip maps definition or similar.

**Comment by vanlueckn** [comment]
Yes the logs contains errors about importing the texture: https://img.vanlueck.dev/Qlwtg9YlExyN

The texture itself was exported with nvidia dds exporter and works in gta5. So OpenIV and the game are able to read the texture and the mipmaps.

**Comment by DurtyFree** [comment]
Weird, can you please upload the YTD here?

**Comment by vanlueckn** [comment]
Github does not support ytd uploads, i uploaded the file to a server: https://img.joni.solutions/test.ytd

**Comment by DurtyFree** [comment]
Should be fixed next version
