### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by DraigNET** [DurtyFree/durty-cloth-tool#153]
I have the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at q9DXreEXx7wa4Ksa7r9.zFTF67EMAWhaIXhHIyZ.AX9jnbdyEOEHEaFY8WFW(Object , Object )
   at q9DXreEXx7wa4Ksa7r9.zFTF67EMAWhaIXhHIyZ.HDmEPSCWHL(FVDAR4Inbhj2HAlCE09  , String  , String  , String  , String  , ProgressDialog  )
```

App Version: **2.5.1.0**
Items: **1 project items (1C / 0D)**
Project targets: **3**
DLC name: **adminhoodie**
Collection name: **top // **
Project path: **E:\Game Development\Engines\RageMP\MirageRoleplayV\client_packages\game_resources\dlcpacks\cloth\AdminHoodie\clothproject_AdminHoodie**
Output path: **E:\Game Development\Engines\RageMP\MirageRoleplayV\client_packages\game_resources\dlcpacks\cloth\AdminHoodie**
Disable Extra Ymt Creation: **False**
Create Subfolder For Cloth Drawable Types: **False**
Replace settings enabled: **False // DLC: NoDlc**
Save File Version: **0**
```

Cloth files:
`[Please provide cloth files (ydd, ytd), cloth project and any other related files here]`

**Comment by DurtyFree** [comment]
Please use latest version 2.5.1.1
