### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by 5454Rnf** [DurtyFree/durty-cloth-tool#154]

**Comment by DurtyFree** [comment]
This is not even Durty Cloth Tool.

**Comment by 5454Rnf** [comment]
> นี่คือเครื่องมือผ้า Durty

Sorry I sent it wrong

**Comment by 5454Rnf** [comment]
> นี่ไม่ใช่แม้แต่เครื่องมือผ้า Durty

But let me report it to you. https://github.com/DurtyFree/altv-cloth-tool

**Comment by 5454Rnf** [comment]
![Screenshot (208)](https://github.com/DurtyFree/durty-cloth-tool/assets/117994095/21bcf3ad-950b-4abe-9ba3-f27e6ad6f4e0)

how
