### ISSUE TITLE
Autosave of the Animation and Preview Option

### ISSUE THREAD

**Issue by Kedu1209** [DurtyFree/durty-cloth-tool#161]
In the last Update (2.5.1.1), you didnt had to select these Option everytime you switch to another Texture or Model... now (2.5.2.0) its different and everytime you change Model/Texture the Option resets and you need to set it new manually...

Is it possible to put it back to the "old" System, so you dont need  to select the Options everytime?

**Comment by DurtyFree** [comment]
Hi there, thank you for this suggestion

Yes I'll take note 👍

**Comment by Kedu1209** [comment]
Works with the new Patch again ❤️ Ty

**Comment by Kedu1209** [comment]
Works again ❤️
