### ISSUE TITLE
[Feature Request] Add 'Floor' to Previewer

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [DurtyFree/durty-cloth-tool#168]
Add a 'plane' (solid flat object) to the Cloth Previewer, which indicates the ground level. If the high heels sink into this floor, users will be required to adjust the height, which would also need to be implemented alongside this feature.

Users could toggle this plane on and off too.

**Comment by DurtyFree** [comment]
Will be part of next update

**Comment by TayMcKenzieNZ** [comment]
🔥🔥🔥🔥

**Comment by DurtyFree** [comment]
Added in https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.3.0
