### ISSUE TITLE
Props (hats/glasses) generate no YMT

### ISSUE THREAD

**Issue by mago1337** [DurtyFree/durty-cloth-tool#18]
When trying to create clothing comprised of only hats and glasses, no YMT is generated.

**Comment by DurtyFree** [comment]
Can somebody else investigate / reproduce this same issue?

**Comment by VictorFerraresi** [comment]
Confirming here. Tried with 3 different mods (all hats btw).

**Comment by vitorvasc** [comment]
Yes, I tried with a lot of different models of hats and had the same issue.

**Comment by benzon** [comment]
Yep i can confirm it to, this is a issue with out doubt.

**Comment by medNul** [comment]
Any status on this yet?

Thanks.

**Comment by DurtyFree** [comment]
Fixed in next release, keep an eye on https://github.com/DurtyFree/durty-cloth-tool/releases

**Comment by DurtyFree** [comment]
Latest version that should fix this is now available here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.1
