### ISSUE TITLE
[Feature Request] Application Dark Mode Feature

### ISSUE THREAD

**Issue by bLAstTMF** [DurtyFree/durty-cloth-tool#182]
Can we get a feature where we can make the application dark? I ask this because this bright white background in the dark is screaming bright to the eyes, and plus I think a dark mode most people would prefer over the light mode.

![just a idea](https://github.com/DurtyFree/durty-cloth-tool/assets/161069719/5d2c7ced-6009-4d78-848e-8151fd952052)

**Comment by DurtyFree** [comment]
Hi there, its indeed planned for the upcoming update with UI overhaul, stay tuned :)

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
