### ISSUE TITLE
The assembly is not working

### ISSUE THREAD

**Issue by Mira0Z** [DurtyFree/durty-cloth-tool#196]
I collect caps and glasses, but when they are completed on the server, they remain in the body.
Everything worked the first time, but all the other times it doesn't work out right. 
The model of the hat and glasses remain in the body or give an error.  What is the problem?
The models are taken from other RP servers and should work

**Comment by Mira0Z** [comment]
Hats and glasses*

**Comment by DurtyFree** [comment]
Hi there please use our cloth tool questions channel on our discord for support @ https://discord.plebmasters.de
