### ISSUE TITLE
How to use the Open Sorce program (As there is no .exe or relevant file to compile or make the program work (v2.5.0)

### ISSUE THREAD

**Issue by liam6080** [DurtyFree/durty-cloth-tool#215]
Hello,
I am new to all of this and there is no documentation on how this program works or run.
I am needing some help on how to get it working and running thanks.

**Comment by DurtyFree** [comment]
There is no support for the OS version

**Comment by liam6080** [comment]
Hello,
You don't include any way on the how too compose or start this program.
There is no .exe included and the files are all in a jumble, As long as you can tell me the simple way on how this program starts that will help me a lot, As having a Open Source Program that dose not include a  way on how to compose nor a .exe file to start it is not very good in my eyes.
I would be more then happy to use a newer version if you give me a open source license for it, It is just the older Version does not have a way to even start it nor is there any docs on how to compose it (I don't know anything about this}.
