### ISSUE TITLE
ragemp DLC build causing crash

### ISSUE THREAD

**Issue by VenomSA** [DurtyFree/durty-cloth-tool#224]
Ragemp crashes when creating a dlc with clothes

Repro: include both male and female clothes, set high heels to one pair of shoes from female and then try to build project for Ragemp

Start the server and you'll notice your game will crash when entering

If building the dlc as Singleplayer resource then it'll work but the high heels option won't be available anymore. 

I think the problems comes from the YMT being shared between male&female because this works fine if splitting dlc's and building for ragemp , one for male one for female

**Comment by DurtyFree** [comment]
Hi @VenomSA pls provide an example project, feel free to send it to me via Discord @durtyfree

**Comment by DurtyFree** [comment]
I will close this as unresolved for now, please recreate with more details and reproduction steps in the new v3 update.
