### ISSUE TITLE
YMT Limit Changes for New GTA Update?

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [DurtyFree/durty-cloth-tool#237]
I know the FiveM build isn't technically out yet. But I just wanted to see if you guys know if there will be a new YMT limit due to the update the other day. I know it adds some clothing and stuff. I have a huge EUP project to do and don't want to waste all the time doing it if we are losing yet another YMT or two.

**Comment by iSentrie** [comment]
If it adds new clothing it means it will have lower YMT limit.

**Comment by DurtyFree** [comment]
Hi @Legacy-TacticalGamingInteractive yes it should already be updated in the wiki article. this Update as always used some YMT slots, feel free to read this for more info: https://github.com/DurtyFree/durty-cloth-tool/wiki/YMT-Game-Limit-And-Crash-Issues
