### ISSUE TITLE
Addtl. Sort Option suggestion

### ISSUE THREAD

**Issue by alyxaugustine** [DurtyFree/durty-cloth-tool#241]
This is a minor QOL thing

I organize my cloth packs so that each drawable section is sorted by clothing type. For example the JBIB category is sorted so that all dresses are grouped together, all tops, all jumpsuits, etc..

An addition I would like to suggest is the ability to sort each category by their labels. Combined with the feature to resort their item numbers I believe this could be pretty helpful to my workflow, though I'm unsure of how many others are sorting their cloth packs like this. This organization is super useful for knowing where an item is pretty quickly if i need to replace it or remove it, in addition to providing for a more organized experience in game as well. I have attached some screenshots for reference. 

![Screenshot 2024-07-11 112205](https://github.com/DurtyFree/durty-cloth-tool/assets/127247947/036db6cf-6aa1-4075-8b01-7d9401ba7675)
![Screenshot 2024-07-11 112312](https://github.com/DurtyFree/durty-cloth-tool/assets/127247947/502db807-a37f-4d87-82f4-b35fabe88a7a)

**Comment by DurtyFree** [comment]
Hi there, we area already shipping changes to the way clothes are organized in the upcoming update, feel free take take a look at our #wip-stuff channel on our Discord and see whether this could already improve your workflow

Hope this helps! Will keep this open until clarification

**Comment by DurtyFree** [comment]
Released in v3 update: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
