### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by LittleMsBittles** [DurtyFree/durty-cloth-tool#266]
Hello! 
I have been using durtycloth for a while now and made a comment in the discord asking about dark mode - I was told it was going to be added with the next update at the time I was told a week; that was about a month ago. No rush, I just wanted to make a suggestion about it as a little reminder. I love this application so much, it is literally a game changer. 
Thank you all so much for your hard work on this!

**Comment by DurtyFree** [comment]
Hi there thank you for the feedback, the update will be released upcoming week. Its been in its final tests to ensure everything works out smooth.

#220 #182

I will close this ticket, thank you!
