### ISSUE TITLE
Crash virginia-october-hydrogen

### ISSUE THREAD

**Issue by VeroSnook** [DurtyFree/durty-cloth-tool#267]
Hello everyone,

As soon as I add a clothing pack created by dusty clothe tool, my character crashes when connected with this message: virginia-october-hydrogen

I can't figure out what the problem is.

Thank you for your help.

**Comment by VeroSnook** [comment]
i work whis FiveM

**Comment by DurtyFree** [comment]
Hi please use our discord for such support, thank you!

https://discord.plebmasters.de
