### ISSUE TITLE
Playback speed reverts to 1.00 when the drawable / texture is changed.

### ISSUE THREAD

**Issue by Zackaery** [DurtyFree/durty-cloth-tool#282]
I'm trying to set the playback speed to 0.5 because I'd like to see if the clothing is flawed in any points, and it's easier to notice it in slow motion.

Any time I change the drawable or texture, it reverts back to 1.00

**Comment by DurtyFree** [comment]
Fixed in patch .3, either update thru the auto updater or grab the latest release from: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
