### ISSUE TITLE
Closing with no error

### ISSUE THREAD

**Issue by PeEcEeChIP** [DurtyFree/durty-cloth-tool#29]
For some reason when I got to select a file, it just closes out with no error message at all.

This is how my files look currently.
![image](https://user-images.githubusercontent.com/20268209/135547958-2f644a9d-5a0c-4b59-aaca-9724f64b186a.png)

**Comment by DurtyFree** [comment]
Hi, can you pls zip the files and upload it here. Also explain what you do (What exactly you click) pls

**Comment by C0kkie** [comment]
the ydds missing the prefix

**Comment by DurtyFree** [comment]
> 
> 
> the ydds missing the prefix

But it should work too with that (Atleast I wanted that)

**Comment by PeEcEeChIP** [comment]
So I upload all the .ydd file's, and it'll just close out for ones that jsut have jbib_001 nothing else like p_ or r_ it just closes it out.

**Comment by DurtyFree** [comment]
@PeEcEeChIP You need to provide me the files that cause it to crash / close without errors. I can't fix this otherwise

**Comment by PeEcEeChIP** [comment]
[USMC.zip](https://github.com/DurtyFree/durty-cloth-tool/files/7274510/USMC.zip)

**Comment by DurtyFree** [comment]
Can't reproduce this with latest version.
Closed
