### ISSUE TITLE
Cannot Mass Delete items

### ISSUE THREAD

**Issue by LittleMsBittles** [DurtyFree/durty-cloth-tool#292]
![Screenshot_284](https://github.com/user-attachments/assets/6a88bab1-df50-48cb-82ff-f9f228fbf7a7)
Hello! I added a screenshot. I don't know if it was intentional or not, but you can no longer delete more than one item at a time. If it was intentional, it would be nice to have it back, but either way thank you!

**Comment by DurtyFree** [comment]
Fixed in patch .5, either update thru the auto updater or grab the latest release from: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
