### ISSUE TITLE
.YMT file is not added to .RPF for SIngleplayer RPF

### ISSUE THREAD

**Issue by DerOggy** [DurtyFree/durty-cloth-tool#3]
When creating a singleplayer .RPF file, the .YMT that is created for both FiveM and AltV is not  added to the DLC that is created.

**Comment by DurtyFree** [comment]
Fixed in next release, keep an eye on https://github.com/DurtyFree/durty-cloth-tool/releases

**Comment by DurtyFree** [comment]
Latest version that should fix this is now available here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.1
