### ISSUE TITLE
Mask Not Loading In Alt:V

### ISSUE THREAD

**Issue by GianniVDeLuca** [DurtyFree/durty-cloth-tool#30]
The mask are having the same issues with not showing up in-game. I could get everything else to work but to masks. It's must be having the same issues as the pants.

**Comment by DurtyFree** [comment]
Masks seem to work for many users, do you have example model & texture + how screenshot of how you set it up in the tool?

Did you also try to do it only with the masks?

**Comment by GianniVDeLuca** [comment]
Hello DurtyFree, I hope all is well. I appreciate the fast response. I did add a few different things and they seem to be working except the masks. I will provide some screenshots below of what I have and how it is set up. Is there a Discord for support if this issue still persist? 

![Screenshot 2021-11-01 224426](https://user-images.githubusercontent.com/93520151/139778774-99ec0e4b-bc75-4aa8-a2ed-cefbe14b4609.jpg)
![Screenshot 2021-11-01 224448](https://user-images.githubusercontent.com/93520151/139778776-e6751091-fe9f-42a3-8c84-08075a6cbba1.jpg)
![Screenshot 2021-11-01 224509](https://user-images.githubusercontent.com/93520151/139778778-655f803e-55f0-4b44-a536-51b2ca043e74.jpg)
![Screenshot 2021-11-01 224647](https://user-images.githubusercontent.com/93520151/139778779-641605af-5816-4a07-abee-4744023c966d.jpg)
![Screenshot 2021-11-01 224708](https://user-images.githubusercontent.com/93520151/139778781-54eae117-fec1-4a4b-b4f9-8ab4c5ff09a0.jpg)
![Screenshot 2021-11-01 224721](https://user-images.githubusercontent.com/93520151/139778782-409f1b38-e339-428f-9010-86dce1cbf1f1.jpg)
![Screenshot 2021-11-01 224749](https://user-images.githubusercontent.com/93520151/139778783-8ef35d9c-9ee2-4c11-8224-840f749a3782.jpg)
![Screenshot 2021-11-01 224810](https://user-images.githubusercontent.com/93520151/139778785-625844db-6322-476b-8c7e-4c105c4899d9.jpg)
![Screenshot 2021-11-01 224834](https://user-images.githubusercontent.com/93520151/139778786-b45e5bd4-f3e5-4553-bca2-8392aba92830.jpg)
![Screenshot 2021-11-01 224344](https://user-images.githubusercontent.com/93520151/139778787-2dbdd116-9848-49dc-b37b-a24b92fa99e7.jpg)

**Comment by DurtyFree** [comment]
Hi, you are using the old tool which is not supported anymore. Get the latest tool from our releases page https://github.com/DurtyFree/durty-cloth-tool/releases/latest

**Comment by GianniVDeLuca** [comment]
Awesome, I just updated it, I do apologize about that. I thought I had the most up to date version. Can you tell me if this looks correc
![Screenshot 2021-11-02 224943](https://user-images.githubusercontent.com/93520151/140005062-1b0f419b-3e5d-4898-86a4-4a8156e78589.jpg)
t?

**Comment by GianniVDeLuca** [comment]
Everything appears to be working fine and properly. Thanks a lot. Enjoy the rest of your day.

**Comment by DurtyFree** [comment]
Nice, thx for the feedback
