### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by Senseypico** [DurtyFree/durty-cloth-tool#31]
I have the following error:
System.IO.DirectoryNotFoundException: Část cesty C:\Users\sense\Desktop\obleceni\male\nove\ring\teef_024_u.ydd nebyla nalezena.
   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   v System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   v altClothTool.App.Builders.FivemResourceBuilder.CopyClothModelToResource(ClothData clothData, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix, String yddPostfix) v H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\FivemResourceBuilder.cs:řádek 67
   v altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) v H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:řádek 51
   v altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) v H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:řádek 28

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Please use the latest tool version and make sure that all files exist. (In this case teef_024_u.ydd doesnt exist in the folder anymore..
