### ISSUE TITLE
Durty V2 to V3 clothing numbers unsyned.

### ISSUE THREAD

**Issue by LemonzPCMR** [DurtyFree/durty-cloth-tool#310]
I have 4 clothing packs, on patches I am very careful not to add in new assets and only replace assets. In pack 3 I have like 20 reserve dummy slots for future community requested items. 
So when we moved from Durty V2 to V3 some how most of the male clothing got pushed +20 numbers, I cant pin point exactly where it happened in the packs but here are the numbers I have come up with.
![image](https://github.com/user-attachments/assets/45b3c387-bb45-4566-ad05-84dabc8662e1)

**Comment by DurtyFree** [comment]
Hi @LemonzPCMR does it just shift them in DCT or also ingame? Ingame the only reason can be related to another cloth resource loaded inb4 or the game build has been changed. Similarly for DCT the reasons can be either changed gamebuild in build settings or some drawable id data change I made in this version. Afterall the drawable IDs are currently not reliable (see #120) and will be in the future fixed. 
I recommend to always stick to the relative ids provided in DCT (prefixed with R (R100 etc))

**Comment by LemonzPCMR** [comment]
The packs seem fine and the original builds of the pack had 3 patches without any shuffling. But the first build after V3 release the numbers changed like that so I havnt been able to do any patches. Along with our MEMALLOC crashing were going to have to push it and reconfig our scripts again. Were using 3095 for all builds of the pack and the server has been on the build throughout this packs lifetime.

**Comment by DurtyFree** [comment]
Doesnt seem to be a DCT bug.
