### ISSUE TITLE
[SUGGESTION] Copy/Duplicate drawable to another type

### ISSUE THREAD

**Issue by Crushinkill** [DurtyFree/durty-cloth-tool#312]
Being able to copy/duplicate a drawable from one type to another, not to move it to another type but to have it copied in that second type for those who want an asset available in multiple slots, like both accs and decal. This would be a big time saver for myself.

**Comment by DurtyFree** [comment]
Fixed in latest release Hotfix .8, get it from here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.0.0.0
