### ISSUE TITLE
Incorrect paths in fxmanifest

### ISSUE THREAD

**Issue by uvanov** [DurtyFree/durty-cloth-tool#32]
After building project i got this in fxmanifest.lua

![Screenshot_5](https://user-images.githubusercontent.com/54040921/141347344-24dd8fef-eba9-4f4e-905b-6c34c1836999.png)

**Comment by DurtyFree** [comment]
Which version of the tool are you using?

**Comment by DurtyFree** [comment]
Closing this as its related to some old version of the tool.
