### ISSUE TITLE
Addon EUP FiveM Crash on Loading into Server v3.0.7

### ISSUE THREAD

**Issue by Gawls** [DurtyFree/durty-cloth-tool#321]
I'll preface with saying that I've used durty on and off for about a year now. I think it's an awesome tool.

**Issue**:  When I build addon EUP packs and move it to the server, players crash when loading in.  The crash happens after the loading screen but before the multi-character screen.

**Things I've Tried**:  At first I thought it was maybe one of the models/textures so I tried different combinations and the same result occurred.  I rebuilt a project that I built using a previous version of durty and it still crashed at the same point.  I've tried removing the pedalternatevariations.meta, but that didn't help either.  I tried running durty with admin perms, no change.  I tried re-downloading durty, no change.  I tried rolling back durty but the auto-updater forced me to update.

![Screenshot 2024-09-13 122937](https://github.com/user-attachments/assets/2b1cf2af-04f8-40f6-84fe-9d1bad54ca88)

Crash Log

[CitizenFX_log_2024-09-13T175950.log](https://github.com/user-attachments/files/16998059/CitizenFX_log_2024-09-13T175950.log)

**Comment by Gawls** [comment]
I've resolved this error.  I believe this had to with the number of packs I had in the server. I consolidated some packs and we can fly in again.  But strange that my test pack I tried was already in the server...

**Comment by DurtyFree** [comment]
Happy to hear it is resolved, thank you!
