### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by chiemisami** [DurtyFree/durty-cloth-tool#323]
![image](https://github.com/user-attachments/assets/3a2da230-63ef-4d2a-8c28-6fe1773a4802)

I keep getting this error when trying to load up projects. It keeps locking up Durty Cloth and I have to uninstall and reinstall to try and start a new project or open a different one.

**Comment by DurtyFree** [comment]
Hi @chiemisami I hope this has been resolved with the latest version. If not please contact me via direct message on Discord @DurtyFree so we can get this resolved.

Thank you!
