### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by Alexert97** [DurtyFree/durty-cloth-tool#33]
I have the following error:
System.OverflowException: Valore troppo grande o troppo piccolo per un Unsigned Byte.
   in System.Byte.Parse(String s, NumberStyles style, NumberFormatInfo info)
   in System.Convert.ToByte(String value)
   in CodeWalker.GameFiles.XmlMeta.Traverse(XmlNode node, MetaBuilder mb, MetaName type, Boolean isRoot)
   in CodeWalker.GameFiles.XmlMeta.TraverseArrayStructure(XmlNode node, MetaBuilder mb, MetaName type)
   in CodeWalker.GameFiles.XmlMeta.TraverseArray(XmlNode node, MetaBuilder mb, MetaStructureEntryInfo_s arrEntry, Int32 offset, ArrayResults results)
   in CodeWalker.GameFiles.XmlMeta.Traverse(XmlNode node, MetaBuilder mb, MetaName type, Boolean isRoot)
   in CodeWalker.GameFiles.XmlMeta.GetMeta(XmlDocument doc)
   in Oh5F0XF14QouHg5cpOp.Ov884mQrYV(XmlDocument , Oh5F0XF14QouHg5cpOp )
   in YfvOnSGihwa8OLGjLUL.Bs7UqGGUjB1ySC8fe5A.q01Gs4aunn(String  , List`1  )
   in lRWLthGT8fOuEOU43lg.FMedXPGP8x8Z2d6RO5V.RQxREWA9MV(String  , String  )
   in e0n89PGMTgqHFRgf6mm.dhKaISGcAmyqT9Z0qX8.vCp772t9hRvib5onfw5(Object , Object , Object )
   in e0n89PGMTgqHFRgf6mm.dhKaISGcAmyqT9Z0qX8.SPNGAE9M7V(TargetResourceType  , String  , String  )

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Please provide cloth files and your cloth project, seems to be an issue with reading some of your files?

**Comment by DurtyFree** [comment]
Cloes as there have not been any activities.
