### ISSUE TITLE
Server Crash on server startup

### ISSUE THREAD

**Issue by khaosen** [DurtyFree/durty-cloth-tool#336]
I converted a simple 1 ydd 1 ytd model to a fivem resource using the tool and it crashes the entire server upon running. I am attaching the resource and can provide the crash dump & project if requested.
https://cdn.discordapp.com/attachments/713818618663534684/1290381122106032242/lssd_mask.rar?ex=66fc4091&is=66faef11&hm=038cb9db2a4730b7b346d53f969c147c153148a99350b8de97ff09b22548f7fc&

**Comment by khaosen** [comment]
I'd also like to note that it only crashes the server if I set the prop model to the Mask option. When I set it to head to test, it doesn't show up but it doesn't crash either.

**Comment by DurtyFree** [comment]
Hi @khaosen please send me the related cloth project in dctexport format via DM on Discord

In before please make sure the crash is 100% reproduceable with just the cloth resource output and nothing else loaded on the server (besides maybe vmenu) - thank you!

**Comment by khaosen** [comment]
> Hi @khaosen please send me the related cloth project in dctexport format via DM on Discord
> 
> In before please make sure the crash is 100% reproduceable with just the cloth resource output and nothing else loaded on the server (besides maybe vmenu) - thank you!

DM'ed you - Discord is khaosen

**Comment by DurtyFree** [comment]
User runs many small cloth resources with just couple of clothes each, most likely hitting the game limit. Not a DCT issue
