### ISSUE TITLE
Error Crash

### ISSUE THREAD

**Issue by Elroww** [DurtyFree/durty-cloth-tool#341]
![Capture d’écran 2024-10-10 211030](https://github.com/user-attachments/assets/831c28ba-f1a1-4e1b-ab2f-4c532e5fb08d)
![2](https://github.com/user-attachments/assets/2bd1ebbe-356f-4832-9d7d-44b1060c7b48)
![1](https://github.com/user-attachments/assets/bd8a9a70-2ae4-4fea-8238-4213bcda9368)

**Comment by DurtyFree** [comment]
Resolved / not an issue
