### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by skullsAK** [DurtyFree/durty-cloth-tool#350]
I have the following error:
System.IO.FileNotFoundException: Filen 'C:\Users\emil\Desktop\piss\task_009_u.ydd' blev ikke fundet.
Filnavn: 'C:\Users\emil\Desktop\piss\task_009_u.ydd'
   ved System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   ved System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   ved System.IO.File.Copy(String sourceFileName, String destFileName)
   ved altClothTool.App.Builders.AltvResourceBuilder.CopyClothModelToResource(ClothData clothData, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix, String yddPostfix) i H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\AltvResourceBuilder.cs:linje 70
   ved altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) i H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:linje 51
   ved altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) i H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:linje 18

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Please use the latest Version from https://gta.clothing
