### ISSUE TITLE
Error importing custom named clothing from folders and files

### ISSUE THREAD

**Issue by kayotimoteo** [DurtyFree/durty-cloth-tool#351]
App Version: 3.0.0.8
Project targets: FiveM
DLC name: villa_test
Collection name: ** // **
Project path: D:\DEV\RP\villa_clothes\villa_teste\clothproject_teste_villa
Output path: D:\DEV\RP\villa_clothes\villa_teste
Disable Extra Ymt Creation: False
Create Subfolder For Cloth Drawable Types: False
Replace settings enabled: False // DLC: NoDlc

New installation and new project.

How to Reproduce
1. Create a new project.
2. Click on Add.
3. Add from Folder(s) or Add from File(s).
4. Receive the error: "Didn't find any cloth models (*.ydd) that start with mp_m or mp_f. Try gender specific 'Add from folder' instead" or "Didn't find any cloth models (*.ydd) that start with mp_m or mp_f. Try gender specific 'Add from files' instead."

More details:
https://youtu.be/Ir3vR7bXBTw
![image](https://github.com/user-attachments/assets/ae7d66a7-5d4f-4e0a-ba54-044d42ff2811)

**Comment by DurtyFree** [comment]
Fixed next update

**Comment by DurtyFree** [comment]
Fixed in v3.1 https://github.com/DurtyFree/durty-cloth-tool/releases/tag/3.1.0.0
