### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by Robot4** [DurtyFree/durty-cloth-tool#36]
I have the following error:
System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'accès 'C:\Users\mehdi\OneDrive\Bureau\clothes\Short hairstyle for MP Male by grzybeek\SP\hair_009_u.ydd'.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   à System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   à altClothTool.App.Builders.FivemResourceBuilder.CopyClothModelToResource(ClothData clothData, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix, String yddPostfix) dans H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\FivemResourceBuilder.cs:ligne 67
   à altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) dans H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:ligne 51
   à altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) dans H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:ligne 28

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Cloth tool can't find this file: `C:\Users\mehdi\OneDrive\Bureau\clothes\Short hairstyle for MP Male by grzybeek\SP\hair_009_u.ydd`

This is not an issue and is properly catched with newer versions. Therefore I close this
