### ISSUE TITLE
[SUGGESTION] Adding Decimal Format to Tattoo Rotation

### ISSUE THREAD

**Issue by xViperAG** [DurtyFree/durty-cloth-tool#364]
I was in the midst of doing some add-on tattoos for FiveM and was setting the rotation to the default rotation and noticed that it is strictly set to a static number. Can this possibly be switched for a decimal format to allow for the proper adjusted rotations?

Images:

- This image is from the tattoo being adjusted into an add-on based on the Pleb Masters Forge.
![image](https://github.com/user-attachments/assets/7f877e49-bc13-4e33-b5e7-ea61333cb6af)

- This image is from DurtyClothTool (Current Update).
![image](https://github.com/user-attachments/assets/68811ee7-2503-4a28-927b-0d97d609cd73)

**Comment by DurtyFree** [comment]
Thank for your suggestion, should be available now in Hotfix 3
