### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by r5ptor** [DurtyFree/durty-cloth-tool#39]
I have the following error:
System.IO.IOException: Na disku není dost místa.

   v System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   v System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   v System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   v altClothTool.App.Builders.FivemResourceBuilder.CopyClothModelToResource(ClothData clothData, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix, String yddPostfix) v H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\FivemResourceBuilder.cs:řádek 67
   v altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) v H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:řádek 51
   v altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) v H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:řádek 28

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Some model or texture file seems to be missing or something. please use the latest version of the tool
