### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by IBekrat** [DurtyFree/durty-cloth-tool#40]
I have the following error:
System.UnauthorizedAccessException: Der Zugriff auf den Pfad "C:\dlc.rpf" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   bei System.IO.FileStream..ctor(String path, FileMode mode)
   bei RageLib.GTA5.ArchiveWrappers.RageArchiveWrapper7.Create(String fileName)
   bei altClothTool.App.Builders.SingleplayerResourceBuilder.BuildResource(String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\SingleplayerResourceBuilder.cs:Zeile 163.
   bei altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) in H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:Zeile 23.
![vest5](https://user-images.githubusercontent.com/98725180/151735410-a6bddf01-f328-4868-9b0f-46f1ff10dfd8.jpg)

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
For some reason the tool is not able to access the C:\ path, please choose another output folder.
