### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by Brozovec** [DurtyFree/durty-cloth-tool#41]
I have the following error:
System.ArgumentException: Cesta obsahuje neplatné znaky.
   v System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
   v System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
   v System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   v System.IO.Path.GetFullPathInternal(String path)
   v System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   v System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   v altClothTool.App.Builders.FivemResourceBuilder.CopyClothTextureToResource(String clothTextureFilePath, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix, String ytdPostfix, Char offsetLetter) v H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\FivemResourceBuilder.cs:řádek 60
   v altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) v H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:řádek 56
   v altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) v H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:řádek 28

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Any of your paths contain invalid characters - please check your files and output folder.
