### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by KaVVaski** [DurtyFree/durty-cloth-tool#57]
I have the following error:
System.OutOfMemoryException: Zgłoszono wyjątek typu 'System.OutOfMemoryException'.
   w System.IO.MemoryStream.set_Capacity(Int32 value)
   w System.IO.MemoryStream.EnsureCapacity(Int32 value)
   w System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   w RageLib.Data.PartialStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   w RageLib.GTA5.ArchiveWrappers.RageArchiveResourceFileWrapper7.Import(Stream stream)
   w RageLib.GTA5.ArchiveWrappers.RageArchiveResourceFileWrapper7.Import(String fileName)
   w altClothTool.App.Builders.SingleplayerResourceBuilder.BuildResource(String outputFolder, String collectionName) w H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\SingleplayerResourceBuilder.cs:wiersz 244
   w altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) w H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:wiersz 23

Cloth files: 2,08GB, around 800 models
https://mega.nz/file/b1ZxUQZL#NjoCFti-RR8-L9kgJ-MZJRkpEGPEzK98V56ldCIKuLM

**Comment by DurtyFree** [comment]
Interesting, thanks for reporting! Will look into it when I got time.

**Comment by DurtyFree** [comment]
Considered fixed for the next update until further bug reportings
