### ISSUE TITLE
Tool deletes all desktop items

### ISSUE THREAD

**Issue by nzkfc** [DurtyFree/durty-cloth-tool#62]
SO last year when I was using this tool (out of downloads folder on C:\), while trying to build it threw some errors, after sorting that out I noticed my entire desktop was deleted apart from recycle bin. No a major as I only had shortcuts to a few folders I could recreate.

I've just come to use it again and it's done the same thing, but this time I happened to have a big project folder of various works on my desktop that got wiped, nothing in recycle bin either.

Sounds like this is known and may need to be fixed to avoid issues from other users.

**Comment by DurtyFree** [comment]
Hi there, very sorry to hear this. Its actually something that is already finished for the next update to always put the output in a new folder and never create anything out of its scope.

Deleted files should hopefully be restoreable using some data restore tool :(

**Comment by DurtyFree** [comment]
Introduced in v2.5.0, feel free to check it out & download here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.0
