### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by NaasKoo** [DurtyFree/durty-cloth-tool#64]
I have the following error:
System.IO.FileNotFoundException: Le fichier 'E:\Serveur Trinity\Clothes - Linges\Linge Personnel\Female BB Skintight\jbib_diff_005_a_uni.ytd' est introuvable.
Nom de fichier : 'E:\Serveur Trinity\Clothes - Linges\Linge Personnel\Female BB Skintight\jbib_diff_005_a_uni.ytd'
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   à System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   à altClothTool.App.Builders.FivemResourceBuilder.CopyClothTextureToResource(String clothTextureFilePath, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix, String ytdPostfix, Char offsetLetter) dans H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\FivemResourceBuilder.cs:ligne 60
   à altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) dans H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:ligne 56
   à altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) dans H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:ligne 28

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Please use latest version, get it from https://github.com/DurtyFree/durty-cloth-tool/releases
