### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by LittleTriare** [DurtyFree/durty-cloth-tool#76]
I have the following error:
System.IO.FileNotFoundException: No se pudo encontrar el archivo 'C:\Users\Eva\Desktop\jbib_044_u.ydd'.
Nombre de archivo: 'C:\Users\Eva\Desktop\jbib_044_u.ydd'
   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   en System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   en altClothTool.App.Builders.FivemResourceBuilder.CopyClothModelToResource(ClothData clothData, Int32 sexNr, String outputFolder, String collectionName, String componentNumerics, String prefix, String yddPostfix) en H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\FivemResourceBuilder.cs:línea 67
   en altClothTool.App.Builders.Base.MultiplayerResourceBuilderBase.BuildResource(String outputFolder, String collectionName) en H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\Builders\Base\MultiplayerResourceBuilderBase.cs:línea 51
   en altClothTool.App.ClothesResourceBuilderFactory.BuildResource(TargetResourceType resourceType, String outputFolder, String collectionName) en H:\DevProjects\GIT_Projects\altv-cloth-tool\altClothTool.App\ClothesResourceBuilderFactory.cs:línea 28

Cloth files: [Please provide cloth files (ydd, ytd) and cloth project file here]

**Comment by DurtyFree** [comment]
Please use latest version
