### ISSUE TITLE
Add support for reserving drawable / texture slots (Dummy / placeholder cloths?)

### ISSUE THREAD

**Issue by Fireant456** [DurtyFree/durty-cloth-tool#8]
I am wondering if you can add a "reserve slot" feature similar to GTAUtil where it creates blank dummy slots after your addon items to reserve slots before the DLC clothing so that as you add more clothes later on the slot numbers in game will not change.

**Comment by DurtyFree** [comment]
Similar to GTAUtil? Can you share this from GTAUtil, so I can take a look?

I am not sure yet if this is possible, as such "Reserve / Dummy" placeholder clothes will still be considered as real clothes by the game I guess?

**Comment by Fireant456** [comment]
The reserve slots are basically the small torso t-shirt model repeated over in those slots. GTAUtil just has a variable to set when you generate the built resource. to tell it how many total slots you want so if you are adding 10 addons and you set the reserve to 100 the program adds 90 dummy items. At least from what I can tell, you don't actually need to stream or add any ydd or ytd files for those dummies though.

https://github.com/indilo53/gtautil

**Comment by DurtyFree** [comment]
Is supported in the next gen of this tool, keep an eye on releases page.

**Comment by DurtyFree** [comment]
Latest version that adds this feature is now available here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.1
