### ISSUE TITLE
Male Clothing Crashes Game [FiveM]

### ISSUE THREAD

**Issue by ruleqt** [DurtyFree/durty-cloth-tool#83]
When I add male clothing into my server with the tool, I crash before I can move around
Whereas if I only add female clothing, it works fine.

Is there a fix to this or am I doing something wrong?

**Comment by DurtyFree** [comment]
Please read this; https://github.com/DurtyFree/durty-cloth-tool/wiki/YMT-game-limit-and-crash-issues

I am 99% sure your crash is related to your gamebuild not supporting the amount of addon YMT files.

Feel free to reopen this issue if it doesnt resolve your problem, and pls provide a screenshot of the exception.
Best way to get support with such issues is our discord at https://forge.plebmasters.de/
