### ISSUE TITLE
Masks Flag reset

### ISSUE THREAD

**Issue by TCruxer** [DurtyFree/durty-cloth-tool#85]
Uppon selecting a cut hair flag on any mask it instantly resets whenever you change to another piece of clothing in the tool.

See the gif below for an example:
https://cdn.discordapp.com/attachments/915201286020956180/1025552218780356648/2022-09-30_19-35-29.gif

**Comment by DurtyFree** [comment]
Cut hair is not supported for masks by the game, in the next update this option will completely be removed.

**Comment by DurtyFree** [comment]
Introduced in v2.5.0, feel free to check it out & download here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.0
