### ISSUE TITLE
Pants and shoes textures have wrong name after building dlc (FiveM Resource)

### ISSUE THREAD

**Issue by Dollcia** [DurtyFree/durty-cloth-tool#9]
Hello! 

Today I wanted to make new dlc for my server but apparently I saw one issue with pants and shoes. Even if mine texture files names have "whi", when I build dlc - they became "uni" and doesn't show ingame.

I use fivem resource option.

**Comment by nikit0** [comment]
i have the same error!

**Comment by BaspelOp** [comment]
Hello!
Idk if I have the same issue but my boots and pants doesn't working as well. I am doing everything according to the instructions. Here's some photos. It looks like they don't have any textures.
![image](https://user-images.githubusercontent.com/77331512/111873780-605efb00-8992-11eb-9486-2a9f982ad072.png)
![image](https://user-images.githubusercontent.com/77331512/111873812-7d93c980-8992-11eb-82ce-10d8a1834066.png)

**Comment by sangyoo91** [comment]
Some shoes are created to be `_u` models. From what I know, the `_u` models allow for higher polygons and textures (from what I've heard). These models while can be added as add-ons, for female `feet` files, they appear to be highheels when a another player looks at them.

In summary, even when I seem to be on the ground, for other players, It will seem as if I'm floating mid-air, as if I'm wearing heels.

**Comment by DurtyFree** [comment]
Pls try with latest version: https://github.com/DurtyFree/altv-cloth-tool/releases/tag/1.3

**Comment by HonzaVu** [comment]
Hey, i have to say the problem still remains. For me its the shoes have bad texture (Yellow one's like the guy up here) i tried the latest version 1.4.1

**Comment by DurtyFree** [comment]
Fixed with new version that will be available soon

**Comment by DurtyFree** [comment]
Latest version that should fix this is now available here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.1
