### ISSUE TITLE
Failed to load project

### ISSUE THREAD

**Issue by MorisatoK** [DurtyFree/durty-cloth-tool#90]
Since I'm on the free version I created a few projects with max 5 drawables and saved them. When I try to load them I get the error `You can't load this project due to your license limits. (max 5 drawables of same type)`. I guess that's a bug, since there are only 5 drawables in the project, and I can only create 5 with the free version anyway.

**Comment by DurtyFree** [comment]
Hi there, this will be fixed next version. Thanks for reporting!

**Comment by DurtyFree** [comment]
Open until next update release

**Comment by DurtyFree** [comment]
Introduced in v2.5.0, feel free to check it out & download here: https://github.com/DurtyFree/durty-cloth-tool/releases/tag/2.5.0
